@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc2xhIiwic3ViIjozLCJpYXQiOjE2NzMxOTE4NjEsImV4cCI6MTY3MzE5MTk4MX0.OVBB4vPO1ZUVh6RClKzGvkNFxzBDmnftBJJ1PCYHdKM

### LOGIN ADMIN ---
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "john",
  "password": "changeme",
  "email": "john@mail.com"
}

### LOGIN USER
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "maria",
  "password": "guess",
  "email": "maria@mail.com"
}

### SIGNUP ---NEW--- USER
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
  "username": "robert",
  "password": "mypassword",
  "email": "robert@mail.com"
}

### LOGIN ---NEW--- USER
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "robert",
  "password": "mypassword",
  "email": "robert@mail.com"
}

### CREATE PROFILE
GET http://localhost:3000/create-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cusername": "deniz",
  "cpassword": "fre123",
  "croles": "user"
}

### GET PROFILE
GET http://localhost:3000/profile HTTP/1.1
Authorization: Bearer {{token}}

### GET USER ONLY - 
GET http://localhost:3000/user-only-route HTTP/1.1
Authorization: Bearer {{token}}

### GET ADMIN ONLY
GET http://localhost:3000/admin-only-route HTTP/1.1
Authorization: Bearer {{token}}

### GET ALL ROLES ROUTE
GET http://localhost:3000/all-roles-route HTTP/1.1
Authorization: Bearer {{token}}

### LDAP LOGIN (TESLA)
POST http://localhost:3000/ldaplogin HTTP/1.1
Content-Type: application/json

{
  "username": "tesla",
  "password": "password"
}

### SIGNUP ---NEW--- USER (TESLA)
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
  "username": "tesla",
  "password": "password",
  "email": "tesla@ldap.forumsys.com"
}

### LOGIN ---NEW--- USER (TESLA)
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "tesla",
  "password": "password",
  "email": "tesla@ldap.forumsys.com"
}