@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYmVydCIsInN1YiI6Mywicm9sZXMiOiJ1c2VyIiwiaWF0IjoxNjczMTYyMjUyLCJleHAiOjE2NzMxNjIyNTd9.qBP3h6PNH7gtZg4Z5ZQ7kFaXzVMg5m9TobSfXaPCMJ4

### LOGIN ADMIN
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "john",
  "password": "changeme",
  "email": "john@mail.com"
}

### LOGIN USER
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "maria",
  "password": "guess",
  "email": "maria@mail.com"
}

### SIGNUP ---NEW--- USER
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
  "username": "robert",
  "password": "mypassword",
  "email": "robert@mail.com"
}

### LOGIN ---NEW--- USER
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "robert",
  "password": "mypassword",
  "email": "robert@mail.com"
}

### CREATE PROFILE
GET http://localhost:3000/create-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cusername": "deniz",
  "cpassword": "fre123",
  "croles": "user"
}

### GET PROFILE
GET http://localhost:3000/profile HTTP/1.1
Authorization: Bearer {{token}}

### GET USER ONLY
GET http://localhost:3000/user-only-route HTTP/1.1
Authorization: Bearer {{token}}

### GET ADMIN ONLY
GET http://localhost:3000/admin-only-route HTTP/1.1
Authorization: Bearer {{token}}

### GET ALL ROLES ROUTE
GET http://localhost:3000/all-roles-route HTTP/1.1
Authorization: Bearer {{token}}